name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag heimsite:latest
